// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1HxWyd_xRlHd0G-qVZaRyvsqSpwOixbQ',
    appId: '1:309126348542:android:e55772ed5bf5e034662faf',
    messagingSenderId: '309126348542',
    projectId: 'money-wisely-5d751',
    databaseURL: 'https://money-wisely-5d751-default-rtdb.firebaseio.com',
    storageBucket: 'money-wisely-5d751.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCBQo7Mz3AxHtzMEvgiRlHZOrZH4HPdVU',
    appId: '1:309126348542:ios:16fb80afe9266651662faf',
    messagingSenderId: '309126348542',
    projectId: 'money-wisely-5d751',
    databaseURL: 'https://money-wisely-5d751-default-rtdb.firebaseio.com',
    storageBucket: 'money-wisely-5d751.appspot.com',
    iosClientId: '309126348542-rkbmq37f3poi6npbr5ecv5kh279lcu34.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyWise',
  );
}
